apiVersion: v1
kind: Service
metadata:
  name: menu-order-service
  namespace: restaurant-app
  labels:
    app: menu-order-service
spec:
  type: NodePort
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
    nodePort: 30003  # Accesibil prin port-forward la localhost:3003
  selector:
    app: menu-order-service

