{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: {{ .Values.namespace.name }}
  labels:
    app: grafana
    {{- include "restaurant-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.grafana.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.grafana.storage.size }}
{{- end }}

