apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  username: {{ .Values.mongodb.credentials.username }}
  password: {{ .Values.mongodb.credentials.password }}


