{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: {{ .Values.namespace.name }}
  labels:
    app: prometheus
    {{- include "restaurant-app.labels" . | nindent 4 }}
{{- end }}

