{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage
  namespace: {{ .Values.namespace.name }}
  labels:
    app: prometheus
    {{- include "restaurant-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.prometheus.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.size }}
{{- end }}

