apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: restaurant-app
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: kafka-external
  - port: 29092
    targetPort: 29092
    protocol: TCP
    name: kafka-internal
  selector:
    app: kafka

